#Saved DB Config
#Sat Feb 07 12:33:10 IST 2026
db.mobile.column=mobile_no
db.type=sqlserver
db.password=Damian@John07
db.port=1433
db.table=customer_data
db.host=localhost
db.name=test_data
db.username=appuser
